### ISSUE TITLE
Send X-VAULT-TRACE-UID HTTP header for session_encrypt and session_decrypt.

### ISSUE THREAD

**Issue by auricsystems** [AuricSystemsInternational/creditcard-tokenizer#11]
The AuricVault service uses a trace Id for end-to-end tracking and debugging. 
Use the Trace ID provided by the user (see https://github.com/AuricSystemsInternational/creditcard-tokenizer/issues/10).

**Comment by auricsystems** [comment]
Documentation on the header:
    
    https://docs.auricvault.com/api-docs/#_x_vault_trace_uid

**Comment by sd0s** [comment]
Added traceId support
